name: Check Text Files

on:
  push:
    branches:
      - master

jobs:

  check-text-files:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check text files
      run: |
        for file in **/*.txt; do
          if [ ! -s "$file" ]; then 
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"title":"Empty Text File Found","body":"The file '$file' in branch ${{ github.ref }} is empty"}' https://api.github.com/repos/${{ github.repository }}/notifications  
          fi 
        done
