name: Example Workflow

on:
  push:
  workflow_dispatch:
  schedule:
   - cron: "0 0,12 * * *"  

jobs:

  run-script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: |
        node index.js > output.txt

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add output.txt
        git commit -m "Add output file"
        git push
