name: test

on: push

jobs: 
    main: 
        runs-os: ubuntu-latest
        steps:
            -run: date
    depend:
        needs: [main]
        runs-os: ubuntu-latest
        steps: 
            -run: date
           
