name: Example 

on: push

jobs:

  run-script:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Node.js  
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies  
      run: npm install

    - name: Run script
      id: runscript
      run: |
        node index.js > output.txt

        SUM=$(cat output.txt | grep "is:" | cut -d' ' -f5)

        echo "::set-output name=sum::$SUM"

    - name: Echo sum
      run: echo "The sum is ${{ steps.runscript.outputs.sum }}"
