name: Collect

on:
  workflow_dispatch:
  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    - cron: "0 0,12 * * *"

jobs:

  run-script:

    runs-on: ubuntu-latest 

    steps:

    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: |
        node index.js > output.txt

    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output-file
        path: output.txt

  download-output:

    needs: run-script

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Download output file
      uses: actions/download-artifact@v2
      with: 
        name: output-file
        path: ./

    - name: Commit file
      run: |        
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add output.txt
        git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Done"
        git push
